### ISSUE TITLE
Version 5.2.0 not available on Docker

### ISSUE THREAD

**Issue by bartversluijs** [balena-io/open-balena-db#41]
Hi,

Version 5.2.0 of the `open-balena-db` is not available on the [Docker Hub](https://hub.docker.com/r/balena/open-balena-db).
Is this an issue with the workflows? Or something else?

Thanks in advance!

**Comment by Page-** [comment]
Hey @bartversluijs this does indeed look like an issue with the GH action workflow, I'm looking into fixing it

**Comment by Page-** [comment]
For the moment I've opened #42 which should publish 5.2.1 to dockerhub which will be equivalent to 5.2.0, I've also asked internally for help on how to fix the 5.2.0 publish itself (at this point it's too late for a simple retry to work)

**Comment by bartversluijs** [comment]
@Page- Thanks for the fast response, will test that version out!

**Comment by Page-** [comment]
It published successfully: https://hub.docker.com/layers/balena/open-balena-db/5.2.1/images/sha256-1ba99dc1757d528bb2ecf22ab026d0c80af8569d33ecb58b12d5615c6f1350bd?context=explore
